### ISSUE TITLE
Path handling of xx_database_xx 

### ISSUE THREAD

**Issue by theonov13** [pyflosic/fodMC#5]
For the python interface, xx_database_xx needs every to be in the actual calculation folder.    
This is some home redundant, as only KT can change this file reasonably.   
The fodmc.f90 should have a way to set the path to this file.

**Comment by kaitrepte** [comment]
Good idea. I can have a look at that. Might be an idea to couple that with the python layout?

**Comment by theonov13** [comment]
I "fixed" it very crude in the python interface via io (copy the file and delete it at the end). 
Thus the overall folder structure is clean. 
But it would be nice if the FORTRAN call would have a parameter to set up the path 
or automatically read not from working directory instead using the source code directory for reading the database file.

**Comment by kaitrepte** [comment]
There is a new fodmc.f90, which includes the database file as an executable. This is now updated
