### ISSUE TITLE
"program fodMC" outdated 

### ISSUE THREAD

**Issue by theonov13** [pyflosic/fodMC#6]
Please use the modular FORTRAN file I used for the Python interface 
to design a "program fodMC" based on this module. 
Otherwise, the src routines never have the same developer status.

**Comment by kaitrepte** [comment]
I agree. I will do that once everything else has a proper structure. Then, I might as well just develop the python path, and work on the source code in there.

**Comment by kaitrepte** [comment]
In the new folder structure under 'lib', we now have a fodmc.f90 which has a module that contains the subroutine get_guess(). And the entire fortran program can be executed in the shell if necessary.
