### ISSUE TITLE
Output CLUSTER and FRMORB 

### ISSUE THREAD

**Issue by theonov13** [pyflosic/fodMC#8]
It would be really nice to control the output level with a switch in the input. 

- output = NRLMOL -> CLUSTER, FRMORB 
-  output = PyFLOSIC -> FODMC_GUESS.xyz 

This would give the user maximum control of the output.

**Comment by kaitrepte** [comment]
This is now adjusted. There are two new keywords for the Fortran call, output_mode and output_name. 
output_mode can be NRLMOL or PyFLOSIC. output_name defines the .xyz file in PyFLOSIC.
