### ISSUE TITLE
Permission for making a pip package

### ISSUE THREAD

**Issue by theonov13** [pyflosic/fodMC#9]
Now we have everything to make a fodMC pip package, 
which then can be installed alongside PyFLOSIC_dev. 
I only need your permission to do that.

**Comment by kaitrepte** [comment]
How would this look like? Only the python variant of the code? I.e., only the python folder in the GitHub repro? I would be ok with that, as long as it is easy to update the code.

**Comment by kaitrepte** [comment]
I will restructure the entire repro, to have a consistent layout. Like one examples folder, and all executables in their respective folders. I will think about this some more.

**Comment by kaitrepte** [comment]
Restructuring is done. Local pip installation works, and installation via 'pip3 install fodMC' works as well.
